### PR TITLE
Update Version to 0.2.1

### PR DESCRIPTION
**Pull request by mikemhenry**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by mikemhenry** [comment]
@conda-forge-admin, please rerender

**Review by ijpulidos — APPROVED** [review]
Looks good to me! Thanks.

**Comment by mikemhenry** [comment]
@jchodera When you get a chance can you review this release?

**Comment by mikemhenry** [comment]
@jchodera When you get a chance can you review this release?

**Review by jchodera — APPROVED** [review]
Thanks!

**Pull request merged**
